config:
    payload:
        path: annonceID.csv
        fields:
            - AnnonceID
    target: 'https://refonte.lux-residence.com'
    phases:
        - duration: 10
          arrivalRate: 10
          rampTo: 50
          name: "Warm up the application"
        # - duration: 600
        #   arrivalRate: 50
        #   name: "Sustained max load"
scenarios:
    - flow:
        - get:
            url: "/fr/vente/immeuble/AQUITAINE/33/BORDEAUX/{{ AnnonceID }}/"
